# Generated by Django 5.2.10 on 2026-02-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0005_grievance_assigned_to_grievance_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20),
        ),
    ]
